name: BlockWhitelist
main: de.Herbystar.BlockWhitelist.Main
version: 1.5
author: Herbystar
description: Plugin to prevent custom Block Breaking
commands:
  BWL:
    usage: /BWL
    description: BlockWhitelist Plugin!