name: BlockWhitelist
main: de.Herbystar.BlockWhitelist.Main
version: 1.6
author: Herbystar
description: Plugin to prevent custom Block Breaking
commands:
  BWL:
    usage: /BWL
    description: BlockWhitelist Plugin!
permissions:
  BWL.Bypass:
    description: Bypass the check when breaking a block.